services:
  - type: web
    name: rapport-generator
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: FIREBASE_API_KEY
        sync: false
    healthCheckPath: /index.php